### PR TITLE
Re-add thread library to linker list

### PR DESCRIPTION
**Pull request by cottsay**
Regression caused by 8e354b5aa8281ea8117fc93adb290998b7810be7

Seems to only affect ARM for whatever reason.

Presents with:
```
/usr/bin/ld: CMakeFiles/plasm_loader.dir/plasm_loader.cpp.o: undefined reference to symbol 'pthread_key_delete@@GLIBC_2.4'
/usr/lib/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

Example build break: https://csc.mcs.sdsmt.edu/jenkins/job/ros-jade-ecto_binaryrpm_22_armhfp/8/console

Thanks,

--scott

### CODE REVIEW

**Comment by v4hn** [comment]
:+1:
ecto uses boost::asio which in turn uses a threads implementation.
It seems FindBoost still doesn't offer a way to link against the correct library dependency
when using its templates (http://www.cmake.org/pipermail/cmake/2010-September/039510.html).
The latest recommendation I can find is to manually link with find_package(Threads)
and this is what this request is about.

**Comment by vrabaud** [comment]
thx for that !
